name: On-push to Latest-Release, update Development branch

on:
  push:
    branches:
      - Latest-Release

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git configuration
        run: |
          git config --global user.email "lars@beksoft.dk"
          git config --global user.name "Lars M Bek (automated)"

      - name: Checkout Development
        uses: actions/checkout@v2
        with:
          ref: Development

      - name: Merge Latest-Release into Development branch
        run: |
          git fetch origin LatestRelease # Update the LatestRelease remote tracking branch
          git merge origin/LatestRelease --allow-unrelated-histories # Merge the changes from LatestRelease
          git push # Push the changes to the remote repository

      - name: Checkout Dev-LMB
        uses: actions/checkout@v2
        with:
          ref: Dev-LMB

      - name: Merge Development branch into Dev-LMB branch
        run: |
          git fetch origin Development # Update the Latest-Release remote tracking branch
          git merge origin/Development --allow-unrelated-histories # Merge the changes from Latest-Release
          git push # Push the changes to the remote repository

      - name: Checkout Dev-NJB
        uses: actions/checkout@v2
        with:
          ref: Dev-NJB

      - name: Merge Development branch into Dev-NJB branch
        run: |
          git fetch origin Development # Update the Latest-Release remote tracking branch
          git merge origin/Development --allow-unrelated-histories # Merge the changes from LatestRelease
          git push # Push the changes to the remote repository

      - name: Checkout Dev-MAK
        uses: actions/checkout@v2
        with:
          ref: Dev-MAK

      - name: Merge Development branch into Dev-MAK branch
        run: |
          git fetch origin Development # Update the Latest-Release remote tracking branch
          git merge origin/Development --allow-unrelated-histories # Merge the changes from LatestRelease
          git push # Push the changes to the remote repository

      - name: Checkout Dev-STI
        uses: actions/checkout@v2
        with:
          ref: Dev-STI

      - name: Merge Development branch into Dev-STI branch
        run: |
          git fetch origin Development # Update the Latest-Release remote tracking branch
          git merge origin/Development --allow-unrelated-histories # Merge the changes from LatestRelease
          git push # Push the changes to the remote repository

      - name: Checkout Dev-JSJ
        uses: actions/checkout@v2
        with:
          ref: Dev-JSJ

      - name: Merge Development branch into Dev-JSJ branch
        run: |
          git fetch origin Development # Update the Latest-Release remote tracking branch
          git merge origin/Development --allow-unrelated-histories # Merge the changes from LatestRelease
          git push # Push the changes to the remote repository